### ISSUE TITLE
yellowstone is not precompiled in npm

### ISSUE THREAD

**Issue by yokujin** [mbullington/yellowstone#1]
In README you mentioned 
> ... or you can use Yellowstone precompiled from npm.

but when I tried to use it after `npm install yellowstone` node.js complains:
> Error: Cannot find module 'yellowstone'

I looked through your module and found that `dist` directory does not exist so node cannot load your module. I had to install dev dependencies and compile it by myself. 

Is this intended behaviour?

**Comment by mbullington** [comment]
Fixed in 1.0.1, it was a problem with gitignore. Thanks for pointing that out!
