### ISSUE TITLE
Error in RTSP Data framing

### ISSUE THREAD

**Issue by faugeh** [mbullington/yellowstone#14]
When i 'node examples/wowza.js' to my IP-Cam the following error occurs:

```
Error: Bug in RTSP data framing, please file an issue with the author with stacktrace.
    at RtspClient._onData (/home/.../yellowstone/lib/index.js:171:15)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:266:12)
    at readableAddChunk (_stream_readable.js:253:11)
    at Socket.Readable.push (_stream_readable.js:211:10)
    at TCP.onread (net.js:587:20)
```

It kills the script off during the response to DESCRIBE in CSeq=2.

**Comment by RogerHardiman** [comment]
Can you paste all the log information from the console please.
Also is it possible for you to put this camera online so I can connect directly to it?

**Comment by mbullington** [comment]
Hello,

If you're still having this issue, please feel free to contact either me or Roger privately. Camera access would be great if possible.

From personal experience, I know that a lot of IP cameras cut corners on following protocols. If it's something we can fix within the library, I'd be happy to look into it.

My email is listed on my profile page. Thanks!

**Comment by fbertone** [comment]
Hi,
I'm having the same error with an IP camera and github version of the library.
I wasn't getting the error with npm version (which is quite outdated and does not implement H264Transport)

Full log is:

```
C->S: OPTIONS rtsp://192.168.0.2:554/11 RTSP/1.0
CSeq: 1
User-Agent: yellowstone/2.0.0

23:01:27.172 Video.js:96 S->C: RTSP/1.0 200 OK
CSeq: 1
Server: Hipcam RealServer/V1.0
Public: OPTIONS,DESCRIBE,SETUP,TEARDOWN,PLAY,SET_PARAMETER,GET_PARAMETER


23:01:27.173 Video.js:96 C->S: DESCRIBE rtsp://192.168.0.2:554/11 RTSP/1.0
CSeq: 2
Accept: application/sdp
User-Agent: yellowstone/2.0.0

23:01:27.281 Video.js:96 S->C: RTSP/1.0 200 OK
CSeq: 2
Server: Hipcam RealServer/V1.0
Content-Type: application/sdp
Cache-Control: must-revalidate
Content-length: 416
Content-Base: rtsp://192.168.0.2:554/11/


23:01:27.282 index.js:503 Uncaught Error: Bug in RTSP data framing, please file an issue with the author with stacktrace.
    at RtspClient._onData (index.js:503)
    at emitOne (events.js:96)
    at Socket.emit (events.js:191)
    at readableAddChunk (_stream_readable.js:178)
    at Socket.Readable.push (_stream_readable.js:136)
    at TCP.onread (net.js:560)
_onData @ index.js:503
emitOne @ events.js:96
emit @ events.js:191
readableAddChunk @ _stream_readable.js:178
Readable.push @ _stream_readable.js:136
onread @ net.js:560
23:01:27.284 Video.js:75 TypeError: Cannot read property 'join' of undefined
    at _netConnect.then.then.then.obj (index.js:162)
    at <anonymous>
```

**Comment by RogerHardiman** [comment]
Hi
Is it possible to give me remote access to the camera. Port forwarding 554 is all I need. Drop me a line opensource a-t rjh dot or dot uk

**Comment by fbertone** [comment]
Could you check the address you gave me? Is it rjh dot or dot uk?
Apparently my email was not delivered

**Comment by RogerHardiman** [comment]
Oops. Domain is rjh.org.uk
Thanks

**Comment by fbertone** [comment]
Thanks for the quick feedback!
In my experience I've learned that rtsp "standard" does not really exist out there.

> But it would be great if you could go back to the camera manufacturer and tell them their camera is not RTSP compliant and to get them to fix their camera firmware.

I highly doubt that would have any effect at all!

PS: please consider increasing the version of yellowstone and publish to npm as the last published version is quite old

**Comment by RogerHardiman** [comment]
I've been given Merge permissions so have now added the fix to the Yellowstone source
