### ISSUE TITLE
Example Error

### ISSUE THREAD

**Issue by Charles-Lau-** [mbullington/yellowstone#15]
I tried the example, however , there are two issues, one of which is that the script keep running without a stop, the other is that  the produced h264 file can not be opened by VLC player, is there anything wrong here?

**Comment by RogerHardiman** [comment]
can you give us more information and copy over all the log information shown on the console please?

**Comment by mbullington** [comment]
Hi Charles,

To answer your first question, we haven't looked much into stopping the feed within the library, and this is something I'd like to investigate further in the future. However, with the sample stream, to be quite honest I haven't encountered the end of the video yet. This is definitely something that we should look into.

As for the second question, please look at the README of our latest commit. I added further instructions on how to play the resulting video.

Thanks!
