### ISSUE TITLE
rtsp auth: cannot get realm and nonce

### ISSUE THREAD

**Issue by roccomuso** [mbullington/yellowstone#18]
I'm trying to get data from a rtsp server that requires authentication.
The server replies with this header:

`WWW-Authenticate: Digest realm="DCS-2332L", nonce="d78beaaca45fc3808800a5437772d6dd"`

But the realm and the nonce are not parsed by yellowstone. The [match](https://github.com/mbullington/yellowstone/blob/master/lib/index.js#L272) is null.
Probably this regex `WWW_AUTH_REGEX = new RegExp('([a-z]+)=\'([^,\s]+)\'')` isn't suitable to parse the www-authenticate digest header value.

yellowstone auth request is infact:

`Authorization: Digest username="admin",realm="undefined",nonce="undefined",uri="rtsp://192.168.40.4:554/live1.sdp"`

**Comment by roccomuso** [comment]
The other issue is that you're doing an assignement to a constant variable, [here](https://github.com/mbullington/yellowstone/blob/master/lib/index.js#L275)

**Comment by RogerHardiman** [comment]
Hi
Just ran into the same problem. The code looks to buggy. Like you I fixed the RegEx and can now generate the right type of Authentication string. But when Yellowstone re-sends the RTSP message it includes junk left over from the previous reply.

**Comment by RogerHardiman** [comment]
It's fixed. I also had to use another fix from @smx-smx too
