### ISSUE TITLE
Connect to a normal HTTP server and nothing happens

### ISSUE THREAD

**Issue by ronkorving** [mbullington/yellowstone#2]
Hi, I'm just starting to use this module, so let me start by saying **thanks**! :)

I noticed that I accidentally sent my rtsp request to port 80 on a normal HTTP server. When calling `connect`, my `catch` handler did not fire however (neither did my `then` by the way). So it seems my promise was left in limbo, and after a second or two Node would shut down (no more events left to handle I guess).

**Comment by mbullington** [comment]
I added an error if the response does not conform to the RTSP protocol. But no, this library doesn't support HTTP servers. If the HTTP server doesn't send anything, node shuts down (from my experience also). I think for now, this should be fine.

**Comment by ronkorving** [comment]
Error is what I would expect, thanks :)
