### ISSUE TITLE
other format?

### ISSUE THREAD

**Issue by lanybass** [mbullington/yellowstone#20]
transparent saving?
what if H265 or other format?

**Comment by RogerHardiman** [comment]
I'd love to do H265 but don't have the time.
If you want to implement something in a fork I can check it and merge it into yellowstone.

What did you mean by transparent saving?

Thanks (and sorry for the delay - I don't check the issues very often)

**Comment by RogerHardiman** [comment]
Not heard anything more about what transparent saving was so closing the issue.
