### ISSUE TITLE
where is a documentation?

### ISSUE THREAD

**Issue by anhquoctran** [mbullington/yellowstone#22]
I need a documentation to learn how to use this library

**Comment by RogerHardiman** [comment]
Hi
Unfortunately we have not had time to make any documentation.
When I started using Yellowstone I was already familiar with how RTSP, RTP and H264 video worked so it was easy enough to follow the source code and the example.

But if it is all new to you then the main things are
a) you connect to a server, issue the OPTIONS command, DESCRIBE command, SETUP command and then the PLAY command.
b) you receive video as RTP packets. The library includes code to re-assemble the RTP packets for H264 video back into H264 data
c) It is then down to the user to pass the H264 data into a Decompressor codec to convert H264 data back into images to render on the screen
