### ISSUE TITLE
npm release for 2.1.1

### ISSUE THREAD

**Issue by edykim** [mbullington/yellowstone#23]
I can see some updates on 2.1.1 but it's not on NPM. Could you release the latest change?

Thanks for the awesome work!

**Comment by RogerHardiman** [comment]
I did the changes since 2.1.1 for UDP transport and merged in some Digest Authentication fixes.
But we will need @mbullington to update the NPM

**Comment by mbullington** [comment]
This was fixed with the major release 3.0.1. There are some changes so make sure to check the CHANGELOG. Thanks!
