### ISSUE TITLE
How to get one frame from camera

### ISSUE THREAD

**Issue by PavelKonon** [mbullington/yellowstone#25]
I want to get one frame from camera stream. Could you please help me in this? Because it's not clear.

**Comment by RogerHardiman** [comment]
Yellowstone would give you the compressed video data.  You would get your video frame from the video decoder.

**Comment by RogerHardiman** [comment]
I suspect the author was hoping yellowstone could handle the video payload and did not realise RTSP and RTP are like a road that catries data from server to client but does not know what the data is.

So closing this comment as yellowstone cannot help here. It needs yellowstone PLUS the right video decompressor.
