### ISSUE TITLE
RTSP over Http?

### ISSUE THREAD

**Issue by elvir35** [mbullington/yellowstone#27]
Hi

I have started using your rstp client and managed to get the example running against my IP camera. If I want to tunnel the RTSP stream over http, how much work is needed to change the code in the RTSP client?

**Comment by RogerHardiman** [comment]
I've only had a brief look at using HTTP tunnel mode.
You have to open two HTTP connections to the client (one for sending commands, one for receiving data) and there is a cookie from the Header of the 1st connection that is used in the Header of the 2nd connection to the camera knows they are the same session.

Then data Writes would go into one HTTP session and data Reads would come from the other session.

The rest of yellowstone (generating RTSP commands, parsing then, extracting the RTP data) should not need any changes.
