### ISSUE TITLE
KeepAlive not working on Axis IP camera

### ISSUE THREAD

**Issue by lham** [mbullington/yellowstone#28]
KeepAlive is run using:
https://github.com/mbullington/yellowstone/blob/24fb6444e76f9eb37d1266b31b5515ba788baa6f/lib/RTSPClient.ts#L248-L255

On an Axis IP camera this does not keep the connection alive after running `client.play()` on a connected stream. This is due to the session string not being provided with the keep-alive request. The session typically looks something like `Session: qwertyqwerty;timeout=60`. Their API states the following under the `SETUP` command:

> The response returns a session identifier that should be used together with the stream control commands (for example PLAY, PAUSE and TEARDOWN). If the session header includes the timeout parameter, the session will close after the timeout time unless explicitly kept alive. Session can be kept alive by sending RTSP requests to the Axis product containing the session identifier (for example OPTIONS) within the timeout time or by using RTCP messages.

The current code doesn't keep into account the session string nor the timeout value returned. I believe that it would be an easy fix, though I'm unsure if this is Axis specific or RTSP standard.

As a workaround I'm running the following patch:
```
client.connect(url, { keepAlive: false, connection: 'udp' })
    .then(() => {
        const interval = 1000 * (60 / 3); // 60 is from session, should be parsed instead
        const func = () => {
            this.imageStream
                .request('OPTIONS', { Session: this.imageStream._session })
                .catch(this.onImageStreamConnectionFailure);
        };

        this.imageStream._keepAliveID = setInterval(func, interval);

        return Promise.resolve();
    })
```

**Comment by RogerHardiman** [comment]
Thanks for spotting the requirement for the Session Identifier in the Axis API documentation.

That is a good fix.

I've not got time to merge this into the main source at the moment but thanks for posting the fix.
Roger

**Comment by RogerHardiman** [comment]
I've implemented the fix in the main yellowstone library and tested with an Axis V5915.
Many thanks for the Problem Report
