### ISSUE TITLE
Keep alive not working with Live555 RTSP Proxy Server

### ISSUE THREAD

**Issue by zoolyka** [mbullington/yellowstone#34]
The client is disconnected after 65 seconds.

**Fix:**

Have to send the session id with the OPTIONS requests to keep the current connection/session alive.

`this._keepAliveID = setInterval(() => this.request("OPTIONS", {'Session' : this._session}), 20 * 1000);`

**Comment by RogerHardiman** [comment]
This is now implemented. Many thanks
