### ISSUE TITLE
client.close -> TEARDOWN is broken

### ISSUE THREAD

**Issue by ronkorving** [mbullington/yellowstone#4]
It immediately runs the Promise it sets up for destroying all properties etc, but that promise actually runs before the TEARDOWN is sent. That means the session is gone, the client, everything. The whole thing blows up.

I don't know enough about Babel and Promises to give any sound advice here, but close is really broken.

Log:

```
TEARDOWN undefined RTSP/1.0
CSeq: 1
 { Session: undefined,
  'User-Agent': 'yellowstone/1.0',
  Authorization: 'Basic redacted==' }

/myproject/node_modules/yellowstone/dist/rtsp.js:215
          string += "" + header + ": " + headers[header].toString() + "\r\n";
                                                        ^
TypeError: Cannot read property 'toString' of undefined
```

toString is being run on headers.Session, which is undefined.

**Comment by mbullington** [comment]
I'll take a look at all your issues later today, and see about setting something up for unit tests. This is a relatively new library, thank you so much for all the feedback.

**Comment by ronkorving** [comment]
No worries! I'm happy this even exists :)
