### ISSUE TITLE
Not getting any data

### ISSUE THREAD

**Issue by Tauka** [mbullington/yellowstone#47]
Hello, thank you for this library!

I was able to successfully connect, and can see that RTSP server responding to client commands, but "data" event is not being triggered

Here is my my mediaSource
```
{
  rtp: [ { payload: 96, codec: 'H264', rate: 90000 } ],
  fmtp: [
    {
      payload: 96,
      config: 'profile-level-id=420029; packetization-mode=1; ' +
        'sprop-parameter-sets=Z01AKI2NQDwBE/L/4BegF83AQEBQAAA+gAAMNQ6GACzcAAF9eC7y40MAFm4AAL68F3lwoA==,aO44gA=='
    }
  ],
  type: 'video',
  port: 0,
  protocol: 'RTP/AVP',
  payloads: 96,
  connection: { version: 4, ip: '0.0.0.0' },
  bandwidth: [ { type: 'AS', limit: 5000 } ],
  direction: 'recvonly',
  invalid: [
    { value: 'x-dimensions:1920,1080' },
    {
      value: 'Media_header:MEDIAINFO=494D4B48010300000400000100000000000000000000000000000000000000000000000000000000;'
    },
    { value: 'appversion:1.0' }
  ],
  control: 'rtsp://91.185.5.146:5554/Streaming/Channels/101/trackID=1?transportmode=unicast&profile=Profile_1'
}
```

Here is what DESCRIBE returns
```
C->S: DESCRIBE rtsp://91.185.5.146:5554/Streaming/Channels/101?transportmode=unicast&profile=Profile_1 RTSP/1.0
CSeq: 3
User-Agent: yellowstone/3.x
Accept: application/sdp
Authorization: Basic YWRtaW46QWRtaW4xMjM0

S->C: v=0
o=- 1585669786175060 1585669786175060 IN IP4 10.67.67.33
s=Media Presentation
e=NONE
b=AS:5050
t=0 0
a=control:rtsp://91.185.5.146:5554/Streaming/Channels/101/?transportmode=unicast&profile=Profile_1
m=video 0 RTP/AVP 96
c=IN IP4 0.0.0.0
b=AS:5000
a=recvonly
a=x-dimensions:1920,1080
a=control:rtsp://91.185.5.146:5554/Streaming/Channels/101/trackID=1?transportmode=unicast&profile=Profile_1
a=rtpmap:96 H264/90000
a=fmtp:96 profile-level-id=420029; packetization-mode=1; sprop-parameter-sets=Z01AKI2NQDwBE/L/4BegF83AQEBQAAA+gAAMNQ6GACzcAAF9eC7y40MAFm4AAL68F3lwoA==,aO44gA==
a=Media_header:MEDIAINFO=494D4B48010300000400000100000000000000000000000000000000000000000000000000000000;
a=appversion:1.0
v=0
o=- 1585669786175060 1585669786175060 IN IP4 10.67.67.33
s=Media Presentation
e=NONE
b=AS:5050
t=0 0
a=control:rtsp://91.185.5.146:5554/Streaming/Channels/101/?transportmode=unicast&profile=Profile_1
m=video 0 RTP/AVP 96
c=IN IP4 0.0.0.0
b=AS:5000
a=recvonly
a=x-dimensions:1920,1080
a=control:rtsp://91.185.5.146:5554/Streaming/Channels/101/trackID=1?transportmode=unicast&profile=Profile_1
a=rtpmap:96 H264/90000
a=fmtp:96 profile-level-id=420029; packetization-mode=1; sprop-parameter-sets=Z01AKI2NQDwBE/L/4BegF83AQEBQAAA+gAAMNQ6GACzcAAF9eC7y40MAFm4AAL68F3lwoA==,aO44gA==
a=Media_header:MEDIAINFO=494D4B48010300000400000100000000000000000000000000000000000000000000000000000000;
a=appversion:1.0
```

Here is PLAY
```
C->S: PLAY rtsp://91.185.5.146:5554/Streaming/Channels/101?transportmode=unicast&profile=Profile_1/rtsp://91.185.5.146:5554/Streaming/Channels/101/trackID=1?transportmode=unicast&profile=Profile_1 RTSP/1.0
CSeq: 5
User-Agent: yellowstone/3.x
Session: 159890072

S->C: RTSP/1.0 200 OK
CSeq: 5
Session:        159890072
RTP-Info: url=rtsp://91.185.5.146:5554/Streaming/Channels/101/?transportmode=unicast&profile=Profile_1/rtsp://91.185.5.146:5554/Streaming/Channels/101/trackID=1?transportmode=unicast&profil;seq=37271;rtptime=1707678954
Date:  Tue, Mar 31 2020 15:49:46 GMT
```

And the rest is just bunch of `OPTIONS` requests (every 25s or so)

If you need any extra data, I can provide

I hope you can help me :)

**Comment by RogerHardiman** [comment]
you can grab my email address from www.rjh.org.uk
Send me over a username and password for the camera and I'll take a quick look.
Thanks
Roger Hardiman

**Comment by Tauka** [comment]
Thanks for the quick response!

I cannot seem to reach the website you posted, maybe due to limitations posed by my ISP, could you post your email address here and I will send you credentials

Best
Tauyekel Kunzhol

**Comment by RogerHardiman** [comment]
send it over to opensource@rjh.org.uk

**Comment by RogerHardiman** [comment]
works fine for me.
I modified the wowza example and made 4 changes
  put in the username
  put in the password
  put in the URL
  changed the connection type to tcp

If I try and connect with UDP it does not work. It is possible your RTSP URL needs to be slightly different for UDP connections

**Comment by RogerHardiman** [comment]
Just looked at my Hik cameras - the URL is the same for TCP and UDP
So I expect the issue is just getting UDP packets out of your network.

so you could stick with a TCP connection (RTP over RTSP) for now

**Comment by Tauka** [comment]
Thank you! Changing connection to TCP did the trick!

I wonder if this is gonna affect latency as packet retransmissions might cause overhead?

**Comment by Tauka** [comment]
I will look into server configurations for UDP options

We now can close the issue

**Comment by RogerHardiman** [comment]
Latency... if you have plenty of bandwidth then TCP mode does not add any latency because
A) there is no packet loss and latency comes from having to wait for a re-transmission
B) you have plenty of bandwidth for all the TCP ACK messages to send back to the camera.

I use TCP mode in many projects as it is much easier to pass through the firewall.

**Comment by Tauka** [comment]
Good to know! Yeah, bandwidth shouldn't be a problem in my case
