### ISSUE TITLE
使用海康摄像头的 推流延迟6秒左右    translation... The push stream delay of using Hikvision camera is about 6 seconds

### ISSUE THREAD

**Issue by yh4922** [mbullington/yellowstone#48]

**Comment by RogerHardiman** [comment]
Google translate tells me this says "The push stream delay of using Hikvision camera is about 6 seconds"

**Comment by RogerHardiman** [comment]
It would be good if we had some extra information on your setup and more details on the problem.

**Comment by RogerHardiman** [comment]
no additional information was received, so closing this issue
