### ISSUE TITLE
Onvif backchannel

### ISSUE THREAD

**Issue by theblazehen** [mbullington/yellowstone#63]
Is it possible to use an ONVIF audio backchannel with this library?

Having a glance through the code, doesn't seem like it's currently supported, and would be great to have.

http://www.onvif.org/specs/stream/ONVIF-Streaming-Spec-v210.pdf section 5.3.2

**Comment by RogerHardiman** [comment]
I had started to take a look at the changes and adding the backchannel tag to the DESCRIBE message as an experiment but never finished it off.

At the current time you'd have to implement it yourself but would offer support, code reviews and merging the changes in.

Roger

**Comment by theblazehen** [comment]
Thanks.

Would you be open to considering a bounty for that, as well as an example
application that can play eg an mp3 or any other format that would be
convenient to provide?

**Comment by RogerHardiman** [comment]
A bounty sounds interesting. I don't have any time to even think about it for the next 4 weeks. But someone else may take you up on the offer.

**Comment by RogerHardiman** [comment]
Another software developer @viettel-solutions has contributed the back channel changes.
