### ISSUE TITLE
Seems like the client forgets to use use credentials?

### ISSUE THREAD

**Issue by Leone25** [mbullington/yellowstone#66]
Hello,

I'm trying to use yellowstone to get the video stream from a password protected endpoint. Any time I try to paly it always errors out with a 455 (Method not valid in this state). Inspecting the traffic with wireshark it seems like that the server "forgets to login" at every request and has to do it each time it makes a request thus resulting in a 455 when trying to play. Here is the summary from a dump made with wireshark between yellowstone and an RTSP server:
![image](https://user-images.githubusercontent.com/39310565/179419047-17aabba3-61cf-41e2-94a9-5bb37df91df0.png)
as you can see every time it tries to make a request it first does it without providing credentials which results a 401, and then it does it again, this time with credentials. The first time is fine, if I recall correctly that's what the RTSP specs describes, but the subsequent times it should remember to include an auth header, but it doesn't, thus resulting in a 455 because the server remembers that the SETUP was done on a different session.
For comparison here is one from VLC connection to the same server:
![image](https://user-images.githubusercontent.com/39310565/179419227-ae2e0fc3-40c1-493f-b591-a7a8da45ed4b.png)
As you can see it tries the first time without a credentials, then fails, tries again with credentials, succeeds and then keeps using the same auth header resulting always in a 200.

Can we get a fix for this?

Thank you in advance

Enrico

**Comment by RogerHardiman** [comment]
Thanks for the logs from Wireshark.
I can also see this if I enable the logging in the wowza.js example (the last few lines of the wowza.js file) and point it at one of my CCTV cameras.

I don't think Yellowstone used to work like this in version 2.x
I wonder if something broke when @mbullington moved over to Typescript in 3.x and all I've tested with are Bosch cameras with authentication turned off or with the Wowza online RTSP source (that does not need authentication)

**Comment by RogerHardiman** [comment]
Update: The bug seems to have come from the change by @tuliofaria where it checks for 401 Authentication Errors only on the first two RTSP messages.
I'm testing and working on a fix

**Comment by Leone25** [comment]
great to hear

**Comment by RogerHardiman** [comment]
Or, if you can give me access to the RTSP server you are using, I can do a test here

**Comment by Leone25** [comment]
Unfortunately I can't make the device public, but if you tell me what fork to test with i can try and see if it'll run

**Comment by RogerHardiman** [comment]
fixes are on the master branch

**Comment by Leone25** [comment]
hmmmm something is still wrong 
![image](https://user-images.githubusercontent.com/39310565/189896679-2b51229c-167c-42d8-8d2f-088f2b5c5010.png)
![image](https://user-images.githubusercontent.com/39310565/189896732-a5cb0fd3-4970-4c89-9423-2a1b50998a85.png)

**Comment by RogerHardiman** [comment]
Hi. The SETUP stage is missing. That is wrong. Thanks for the log.

**Comment by Leone25** [comment]
Lmao I didn't even notice

**Comment by RogerHardiman** [comment]
Can you send me the wireshark log of the DESCRIBE packet please, showing the SDP.

**Comment by Leone25** [comment]
sure thing
```
RTSP/1.0 200 OK
CSeq: 3
Content-Type: application/sdp
Content-Length: 507
Date: Wed, 21 Sep 2022 12:37:19 GMT

v=0
o=- 1109162014219182 0 IN IP4 0.0.0.0
s=Media Server V4.26.131
i=Media Server Session Description : standard
e=NONE
c=IN IP4 0.0.0.0
t=0 0
a=control:*
b=AS:1258
a=range:npt=now-
m=video 0 RTP/AVP 96
i=Video Media
a=rtpmap:96 H265/90000
a=control:trackID=video
b=AS:1248
m=audio 0 RTP/AVP 0
i=Audio Media
a=rtpmap:0 PCMU/8000
a=control:trackID=audio
b=AS:10
a=Media_header:MEDIAINFO=494D4B48020100000400050010710110401F000000FA000081000000000000000000000000000000;
a=appversion:1.0

```

**Comment by RogerHardiman** [comment]
I can see the problem.
You are connecting to a H265 (HEVC) video stream.  Yellowstone does not know how to receive RTP packets with H265.
Yellowstone only has code to handle the RTP payloads for H264 and AAC. (the H264Transport and AACTransport files)

So there was a bug in the wowza.js sample that it should not have sent PLAY because there were no streams it could receive.
I've just fixed that in the wowza.js example file.

So, if you need to stream H265, then we need a H265Transport.ts implementation.

(note- there is a nice open source H265Transport in C# in the SharpRTSP project. I wrote it a few years ago)

**Comment by Leone25** [comment]
Well, my idea was to just grab the data from the on data event but sure, that'd be great. From my very limited research i understand that the h265 transport is very similar to h264, obviously decoding is different tho, but that is something I don't have to take care of.

Tho having a dedicated handler would be great.

**Comment by RogerHardiman** [comment]
if you just grab the data from the Data Event, you will not be able to decode and play the video.

The data event will give you the RTP packet contents.
That is a little bit of H265, wrapped with some special headers when sending via RTP. And that data is wrapped in the RTP Packet which adds an extra header.
So you can capture the data from the Data Event, but then you need to write the code to extract the actual H265 video.

**Comment by Leone25** [comment]
Yea i figured, i found a function online that was supposed to be able to extract packets but didn't have much luck so i just ended up using ffmpeg in a "pass through" mode temporary, I'll be waiting for the h265 transport to swap it out.

**Comment by RogerHardiman** [comment]
Ported over my C# H265 RTP handling code to Typescript for 2 of the 3 different ways H265 gets split into packets.
But there is a bug - I get corruption in the H265 from my Axis camera.

So there is something in the h265 branch but needs debugging in H265Transports.ts

**Comment by Leone25** [comment]
Great, I'll test it out, perhaps it works on my machine, worst case scenario I'll try to debug it my self

**Comment by Leone25** [comment]
*little bump in hopes of updates*

**Comment by RogerHardiman** [comment]
remind me what was up. We had the credentials issue and then h265 extraction

**Comment by Leone25** [comment]
correct, you said you were porting your implementation of the h265 extractor but there are still a couple of bugs

i tested it my self, did not work, no idea how to fix the bugs, so i was hoping you could take care of it

**Comment by RogerHardiman** [comment]
I tested the H265 on two cameras yesterday and both worked fine.
I don't know which camera I was using the time before which had the problem.

So I'll merge in the h265 code into the main branch, as it worked on an Axis P5655 and on some HikVision camera I had.
Then if we find something that does not work, I can look into it more.

Would be good to get remote access to your H265 stream

**Comment by Leone25** [comment]
Aright, i tested it again with my local machine and it seems to work now, only issue that i have is that the files stays empty all the time in the example.

I guessed it was because it was a live stream, but even if is just add a timeout with `client.close()` it doesn't save anything (the file is created, but it's always OB), any idea? The terminal clearly suggests that there is data flowing.

**Comment by Leone25** [comment]
If you want i could give you access to my machine trough anydesk, but unfortunately my network doesn't allow me to port forward to the internet

You can dm me on twitter at same name + 03

**Comment by RogerHardiman** [comment]
I don't use twitter. Get my mobile/cell from rjh.org.uk and whatsappme.

**Comment by RogerHardiman** [comment]
I'm +44

**Comment by RogerHardiman** [comment]
Update: There were two issues in this Issue Report
a) a bug in the authentication - now fixed
b) lack of H265 support - now added
Thanks for the remote access
