### ISSUE TITLE
The value of "offset" is out of range. It must be >= 0 and <= 4. Received 16

### ISSUE THREAD

**Issue by ThanosBoulmpos** [mbullington/yellowstone#68]
I am trying to use yellowstone to see the analytics metatadata that are embdedded on the rtsp stream.

Was trying to run the wowza.js example but it looks like that demo rtsp server isn't working anymore. I am trying to use this rtsp stream example :

rtsp://rtsp.stream/pattern

I am getting the following error:
![Screenshot 2022-11-09 at 1 11 17 PM](https://user-images.githubusercontent.com/98536060/200815288-feb8b149-8d3d-4c1b-97b9-e953060da551.png)

Please let me know if you have any idea why this is happening and how can i see the rtsp analytics(metadata) from the stream?

Thank you

**Comment by RogerHardiman** [comment]
Thank you for the issue report.
Would it be possible to get some remote access to the RTSP stream to allow debugging of the connection.

**Comment by RogerHardiman** [comment]
Update - I can see the problem. You will be receiving a RTCP packet that is only 4 bytes long. It looks like the Yellowstone code assumes the RTCP packet is a Sender Report and long enough to read bytes 16,17,18 and 19 from the buffer.
But you have a different RTCP message that is shorter.

I'll try and put in a fix to stop the crash, but would be good to test on the actual stream.

Thanks
Roger

**Comment by RogerHardiman** [comment]
There is a fix in the 'master' branch
