### ISSUE TITLE
Undefined packetLength error and other errors

### ISSUE THREAD

**Issue by RogerHardiman** [mbullington/yellowstone#7]
When I run the yellowstone example I get an error with packetLength not defined.

```
/home/pi/node_modules/yellowstone/dist/rtsp.js:76
      if (packetLength >= 0) {
          ^

ReferenceError: packetLength is not defined
    at RtspClient._onData (/home/pi/node_modules/yellowstone/dist/rtsp.js:76:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)

```

I could fix it by declaring packetLength just before _createClass(RtsClient) in dist/rtsp.js source.
This allowed yellowstone to carry out the initial handstake with the Wowza example (or with my IP cameras) but soon fails when it thorws an exception
throw new Error('unknown protocol? please make sure you are connecting to an rtsp server');

How to reproduce

Did a fresh install on Linux using  npm install yellowstone --save
cd into node_modules/yellowstone directory
ran the example with    node /examples/wowza.js
Running Node v4.0.0

**Comment by dp1140a** [comment]
I received the same error?

**Comment by arodriguezp2003** [comment]
hi the same problem

E:\proyectos\camera\node_modules\yellowstone\dist\rtsp.js:76
      if (packetLength >= 0) {

windows 10

**Comment by mbullington** [comment]
Sorry for the delay, I found the time to majorly refactor/rewrite the library. If you're using Node v6.0.0, feel free to try out v2.0.0 of yellowstone.

Check the CHANGELOG for more details, it now works completely as it says it does, unlike the old version plagued by weird issues (no real data framing, weird copy-paste code, Babel limiting some people from using it, etc).

I apologize for the neglect of this library, but I can now say that it's way more robust and much higher quality.
